services:
  db:
    image: postgres
    container_name: mail-validation-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mail-validation-storage
    ports:
      - "5433:5432"
    networks:
      - mail-validation-network
    volumes:
      - mail-validation-db-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: mail-validation-redis-service
    restart: unless-stopped
    ports:
      - "6380:6379"

networks:
  mail-validation-network:
    driver: bridge

volumes:
  mail-validation-db-postgres-data:
